dist: bionic
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7

script:
  - bundle exec rake spec
  - bundle exec rubocop

# Build gem and show its contents
after_success:
  - bundle exec rake build
  - cd pkg && tar xf *.gem && tar tvf data.tar.gz
